try {
    await log(a, b, c);
} catch (error) {
}

try {
} catch {
}

try {
    a();
    b();
} catch {
}

